package gEapp;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import gEapp.TreeApplication;

import static org.junit.Assert.*;

public class TreeApplicationTest {
    @Test 
    public void testSomeLibraryMethod() {
        TreeApplication classUnderTest = new TreeApplication();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
