package gEapp;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.beans.factory.annotation.Autowired;

import gEapp.domain.Member;
import gEapp.repository.MemberRepository;
import gEapp.service.MemberService;

@SpringBootApplication
public class TreeApplication extends WebMvcConfigurerAdapter implements CommandLineRunner {

	@Autowired MemberRepository memberRepository;
    
	public static void main (String[] args) {
		SpringApplication.run(TreeApplication.class, args);
	}
	
	@Override
	public void run (String... args) throws Exception {

		//Member(Integer id, String name, Integer birthday, String gender,Integer mumKey, Integer dadKey)
		memberRepository.save(new Member(1, "King George VI"));
		memberRepository.save(new Member(2, "Queen Elizabeth"));
		memberRepository.save(new Member(3, "Queen Elizabeth II", null, null, 2, 1));
		memberRepository.save(new Member(5, "Prince Philip Duke of Edinburgh"));
		memberRepository.save(new Member(4, "Princess Margaret", null, null, 2, 1));
		memberRepository.save(new Member(6, "Prince Charles", null, null, 3, 5));
		memberRepository.save(new Member(7, "Princess Diana"));
		memberRepository.save(new Member(8, "Prince William", null, null, 7, 6));
		memberRepository.save(new Member(9, "Prince Harry", null, null, 7, 6));
		memberRepository.save(new Member(10, "Catherine Duchess of Cambridge"));
		memberRepository.save(new Member(11, "Prince George", null, null, 10, 8));
		
	}
	
}
